
import type { Metadata } from "next";
import { Josefin_Sans} from "next/font/google";
import "./globals.css";
import ToastContext from "./context/ToastContext";
import { AuthContext } from "./context/AuthContext";
import BgLinear from "./component/BgLinear";
import ActiveStatus from "./component/ActiveStatus";


const font = Josefin_Sans({
  subsets:["latin"],
  weight:["400", "700"]
}) 
export const metadata: Metadata = {
  title: "Create Messenger App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${font} antialiased`}
      >
        <AuthContext>
          <ToastContext />
          <BgLinear />
          <ActiveStatus />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
